package com.example.bestiarykotlin

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import androidx.recyclerview.widget.LinearLayoutManager
import com.example.bestiarykotlin.databinding.ActivityMainBinding

class MainActivity : AppCompatActivity() {
    private lateinit var binding:ActivityMainBinding
    private lateinit var contentList: ArrayList<ContentDetail>

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding=ActivityMainBinding.inflate(layoutInflater)
        val view=binding.root
        setContentView(view)

        contentList=ArrayList<ContentDetail>()

        //data
        /*
        val beasts=Content("Beasts")
        val cursed_ones=Content("Cursed Ones")
        val draconids=Content("Draconids")
        val elemanta=Content("Elementa")
        val hybrids=Content("Hybrids")
        val insectoids=Content("Insectoids")
        val necrophages=Content("Necrophages")
        val ogroids=Content("Ogroids")
        val relicst=Content("Relicts")
        val specters=Content("Specters")
        val vampires=Content("Vampires")

        contentList.add(beasts)
        contentList.add(cursed_ones)
        contentList.add(draconids)
        contentList.add(elemanta)
        contentList.add(hybrids)
        contentList.add(insectoids)
        contentList.add(necrophages)
        contentList.add(ogroids)
        contentList.add(relicst)
        contentList.add(specters)
        contentList.add(vampires)



         */
        //data

        val abaya=ContentDetail("ABAYA","BIDI BIDI","NECROPHAGES",R.drawable.abaya)
        val alghoul=ContentDetail("ALGHOUL","BIDI BIDI","NECROPHAGES",R.drawable.abaya)
        val alp=ContentDetail("ALP","BIDI BIDI","VAMPIRES",R.drawable.abaya)
        val alpha_garkain=ContentDetail("ALPHA GARKAIN","BIDI BIDI","VAMPIRES",R.drawable.abaya)
        val arachasae=ContentDetail("ARACHASAE","BIDI BIDI","INSECTOIDS",R.drawable.abaya)
        val armored_arachasae=ContentDetail("ARMORED ARACHASAE","BIDI BIDI","INSECTOIDS",R.drawable.abaya)
        val barghest=ContentDetail("BARGHEST","BIDI BIDI","SPECTERS",R.drawable.abaya)
        val basilisk=ContentDetail("BASILISK","BIDI BIDI","DRACONOIDS",R.drawable.abaya)
        val beannshie=ContentDetail("BANSHEE","BIDI BIDI","SPECTERS",R.drawable.abaya)
        val bear=ContentDetail("BEAR","BIDI BIDI","BEASTS",R.drawable.abaya)
        val beast_of_beaculair=ContentDetail("BEAST OF BEACULAIR","BIDI BIDI","BEASTS",R.drawable.abaya)
        val berserker=ContentDetail("BERSERKER","BIDI BIDI","CURSED ONES",R.drawable.abaya)
        val big_bad_wolf=ContentDetail("BIG BAD WOLF","BIDI BIDI","BEASTS",R.drawable.abaya)
        val botchlling=ContentDetail("BOTCHLING","BIDI BIDI","CURSED ONES",R.drawable.abaya)
        val bruxae=ContentDetail("BRUXAE","BIDI BIDI","VAMPIRES",R.drawable.abaya)
        val chort=ContentDetail("CHORT","BIDI BIDI","RELICTS",R.drawable.abaya)
        val cloud_giant=ContentDetail("CLOUD GIANT","BIDI BIDI","OGROIDS",R.drawable.abaya)
        val cocktraice=ContentDetail("COCKTRAICE","BIDI BIDI","BEASTS",R.drawable.abaya)
        val crones=ContentDetail("CRONES","BIDI BIDI","BEASTS",R.drawable.abaya)
        val cyclopse=ContentDetail("CYCLOPSE","BIDI BIDI","BEASTS",R.drawable.abaya)
        val daphne_s_wraith=ContentDetail("DAPHNE'S WRAITH","BIDI BIDI","BEASTS",R.drawable.abaya)
        val detlaff_van_der_eretein=ContentDetail("DETLAFF VAN DER ERETEIN","BIDI BIDI","BEASTS",R.drawable.abaya)
        val devil_by_the_well=ContentDetail("DEVIL BY THE WELL","BIDI BIDI","BEASTS",R.drawable.abaya)
        val devour=ContentDetail("DEVOUR","BIDI BIDI","BEASTS",R.drawable.abaya)
        val djinn=ContentDetail("DJINN","BIDI BIDI","BEASTS",R.drawable.abaya)
        val dog=ContentDetail("DOG","BIDI BIDI","BEASTS",R.drawable.abaya)
        val dopplers=ContentDetail("DOPPLERS","BIDI BIDI","BEASTS",R.drawable.abaya)
        val drowned_dead=ContentDetail("DROWNED DEAD","BIDI BIDI","BEASTS",R.drawable.abaya)
        val drowner=ContentDetail("DROWNER","BIDI BIDI","BEASTS",R.drawable.abaya)
        val earth_elemental=ContentDetail("EARTH ELEMENTAL","BIDI BIDI","BEASTS",R.drawable.abaya)
        val ekhidnae=ContentDetail("EKHIDNAE","BIDI BIDI","BEASTS",R.drawable.abaya)
        val ekimmara=ContentDetail("EKIMMARA","BIDI BIDI","BEASTS",R.drawable.abaya)
        val emiel_regis=ContentDetail("EMIEL REGIS","BIDI BIDI","BEASTS",R.drawable.abaya)
        val endrega_drone=ContentDetail("ENDREGA DRONE","BIDI BIDI","BEASTS",R.drawable.abaya)
        val endrega_warrior=ContentDetail("ENDREGA WARRIOR","BIDI BIDI","BEASTS",R.drawable.abaya)
        val endrega_workers=ContentDetail("ENDRAGA WORKER","BIDI BIDI","BEASTS",R.drawable.abaya)
        val erynias=ContentDetail("ERYNIAS","BIDI BIDI","BEASTS",R.drawable.abaya)
        val ethereal=ContentDetail("ETHEREAL","BIDI BIDI","BEASTS",R.drawable.abaya)
        val fiend=ContentDetail("FIEND","BIDI BIDI","BEASTS",R.drawable.abaya)
        val fire_elemental=ContentDetail("FIRE ELEMENTAL","BIDI BIDI","BEASTS",R.drawable.abaya)
        val fleder=ContentDetail("FLEDER","BIDI BIDI","BEASTS",R.drawable.abaya)
        val foglet=ContentDetail("FOGLET","BIDI BIDI","BEASTS",R.drawable.abaya)
        val forktail=ContentDetail("FORKTAIL","BIDI BIDI","BEASTS",R.drawable.abaya)
        val fugas=ContentDetail("FUGAS","BIDI BIDI","BEASTS",R.drawable.abaya)
        val gael=ContentDetail("GAEL","BIDI BIDI","BEASTS",R.drawable.abaya)
        val gargoyle=ContentDetail("GARGOYLE","BIDI BIDI","BEASTS",R.drawable.abaya)
        val garkain=ContentDetail("GARGAKIN","BIDI BIDI","BEASTS",R.drawable.abaya)
        val ghoul=ContentDetail("GHOUL","BIDI BIDI","BEASTS",R.drawable.abaya)
        val giant_centipede=ContentDetail("GIANT CENTIPEDE","BIDI BIDI","BEASTS",R.drawable.abaya)
        val godling=ContentDetail("GODLING","BIDI BIDI","BEASTS",R.drawable.abaya)
        val golem=ContentDetail("GOLEM","BIDI BIDI","BEASTS",R.drawable.abaya)
        val golyat=ContentDetail("GOLYAT","BIDI BIDI","BEASTS",R.drawable.abaya)
        val grave_hag=ContentDetail("GRAVE HAG","BIDI BIDI","BEASTS",R.drawable.abaya)
        val griffin=ContentDetail("GRIFFIN","BIDI BIDI","BEASTS",R.drawable.abaya)
        val grottore=ContentDetail("GROTTORE","BIDI BIDI","BEASTS",R.drawable.abaya)
        val hagubman=ContentDetail("HAGUBMAN","BIDI BIDI","BEASTS",R.drawable.abaya)
        val harpy=ContentDetail("HARPY","BIDI BIDI","BEASTS",R.drawable.abaya)
        val harrisi=ContentDetail("HARRISI","BIDI BIDI","BEASTS",R.drawable.abaya)
        val hound_of_the_wild_hunt=ContentDetail("HOUND OF THE WILD HUNT","BIDI BIDI","BEASTS",R.drawable.abaya)
        val howler=ContentDetail("HOWLER","BIDI BIDI","BEASTS",R.drawable.abaya)
        val hym=ContentDetail("HYM","BIDI BIDI","BEASTS",R.drawable.abaya)
        val ice_elemental=ContentDetail("ICE ELEMENTAL","BIDI BIDI","BEASTS",R.drawable.abaya)
        val ice_giant=ContentDetail("ICE GIANT","BIDI BIDI","BEASTS",R.drawable.abaya)
        val ice_troll=ContentDetail("ICE TROLL","BIDI BIDI","BEASTS",R.drawable.abaya)
        val ignis_fatuus=ContentDetail("IGNIS FATUUS","BIDI BIDI","BEASTS",R.drawable.abaya)
        val imp=ContentDetail("IMP","BIDI BIDI","BEASTS",R.drawable.abaya)
        val jenny_o_the_woods=ContentDetail("JENNY'O THE WOODS","BIDI BIDI","BEASTS",R.drawable.abaya)
        val katakan=ContentDetail("KATAKAN","BIDI BIDI","BEASTS",R.drawable.abaya)
        val kernun=ContentDetail("KERNUN","BIDI BIDI","BEASTS",R.drawable.abaya)
        val kikimore=ContentDetail("KIKIMORE","BIDI BIDI","BEASTS",R.drawable.abaya)
        val kikimore_worker=ContentDetail("KIKIMORE WORKER","BIDI BIDI","BEASTS",R.drawable.abaya)
        val leshen=ContentDetail("LESHEN","BIDI BIDI","BEASTS",R.drawable.abaya)
        val longlocks=ContentDetail("LONGLOCKS","BIDI BIDI","BEASTS",R.drawable.abaya)
        val lubberkin=ContentDetail("LUBBERKIN","BIDI BIDI","BEASTS",R.drawable.abaya)
        val melusine=ContentDetail("MELUSINE","BIDI BIDI","BEASTS",R.drawable.abaya)
        val moreau_s_golem=ContentDetail("MOREAU'S GOLEM","BIDI BIDI","BEASTS",R.drawable.abaya)
        val morvudd=ContentDetail("MORVUDD","BIDI BIDI","BEASTS",R.drawable.abaya)
        val mourntart=ContentDetail("MOURNTART","BIDI BIDI","BEASTS",R.drawable.abaya)
        val mucknixer=ContentDetail("MUCKNIXER","BIDI BIDI","BEASTS",R.drawable.abaya)
        val nekker=ContentDetail("NEKKER","BIDI BIDI","BEASTS",R.drawable.abaya)
        val nightwraith=ContentDetail("NIGHT WRAITH","BIDI BIDI","BEASTS",R.drawable.abaya)
        val noonwraith=ContentDetail("NOON WRAITH","BIDI BIDI","BEASTS",R.drawable.abaya)
        val opinicus=ContentDetail("OPINICUS","BIDI BIDI","BEASTS",R.drawable.abaya)
        val pale_widow=ContentDetail("PALE WIDOW","BIDI BIDI","BEASTS",R.drawable.abaya)
        val palgue_maiden=ContentDetail("PALGUE MAIDEN","BIDI BIDI","BEASTS",R.drawable.abaya)
        val panther=ContentDetail("PANTHER","BIDI BIDI","BEASTS",R.drawable.abaya)
        val penitent=ContentDetail("PENITENT","BIDI BIDI","BEASTS",R.drawable.abaya)
        val pixie=ContentDetail("PIXIE","BIDI BIDI","BEASTS",R.drawable.abaya)
        val protofleder=ContentDetail("PROTOFLEDER","BIDI BIDI","BEASTS",R.drawable.abaya)
        val red_miasmal=ContentDetail("RED MIASMAL","BIDI BIDI","BEASTS",R.drawable.abaya)
        val rock_troll=ContentDetail("ROCK TROLL","BIDI BIDI","BEASTS",R.drawable.abaya)
        val rotfiend=ContentDetail("ROTFIEND","BIDI BIDI","BEASTS",R.drawable.abaya)
        val royal_wyvern=ContentDetail("RORAL WYVERN","BIDI BIDI","BEASTS",R.drawable.abaya)
        val salma=ContentDetail("SALMA","BIDI BIDI","BEASTS",R.drawable.abaya)
        val sandcrap=ContentDetail("SANDCRAP","BIDI BIDI","BEASTS",R.drawable.abaya)
        val sarasti=ContentDetail("SARASTI","BIDI BIDI","BEASTS",R.drawable.abaya)
        val scurvers=ContentDetail("SCURVERS","BIDI BIDI","BEASTS",R.drawable.abaya)
        val shaelmaar=ContentDetail("SHAELMAR","BIDI BIDI","BEASTS",R.drawable.abaya)
        val shaelmaar_from_the_emperor_of_nilfgaard=ContentDetail("SHAELMAR FROM THE EMPEROR OF NILFGAARD","BIDI BIDI","BEASTS",R.drawable.abaya)
        val shrieker=ContentDetail("SHRIEKER","BIDI BIDI","BEASTS",R.drawable.abaya)
        val silver_basilisk=ContentDetail("SILVER BASILIKS","BIDI BIDI","BEASTS",R.drawable.abaya)
        val siren=ContentDetail("SIREN","BIDI BIDI","BEASTS",R.drawable.abaya)
        val slyzard=ContentDetail("SLYZARD","BIDI BIDI","BEASTS",R.drawable.abaya)
        val slyzard_matriarch=ContentDetail("SLYZARD MATRIARCH","BIDI BIDI","BEASTS",R.drawable.abaya)
        val spotted_wight=ContentDetail("SPOTTED","BIDI BIDI","BEASTS",R.drawable.abaya)
        val spriggans=ContentDetail("SPRIGANS","BIDI BIDI","BEASTS",R.drawable.abaya)
        val succubi=ContentDetail("SUCCUBI","BIDI BIDI","BEASTS",R.drawable.abaya)
        val sylvan=ContentDetail("SYLVAN","BIDI BIDI","BEASTS",R.drawable.abaya)
        val the_apiarian_phantom=ContentDetail("THE APIRIAN PHANTOM","BIDI BIDI","BEASTS",R.drawable.abaya)
        val the_bruxa_of_corva_bianco=ContentDetail("THE BRUXEA OF CORVA BIANCO","BIDI BIDI","BEASTS",R.drawable.abaya)
        val the_caretaker=ContentDetail("THE CARETAKER","BIDI BIDI","BEASTS",R.drawable.abaya)
        val the_dragon_pf_fyresdal=ContentDetail("THE DRAGON OF FYRESDAL","BIDI BIDI","BEASTS",R.drawable.abaya)
        val the_monster_of_tufo=ContentDetail("THE MONSTER OF TUFO","BIDI BIDI","BEASTS",R.drawable.abaya)
        val the_toad_prince=ContentDetail("THE TOAD PRINCE","BIDI BIDI","BEASTS",R.drawable.abaya)
        val the_unseen_elder=ContentDetail("THE UNSEEN ELDER","BIDI BIDI","BEASTS",R.drawable.abaya)
        val the_white_lady=ContentDetail("THE WHITE LADY","BIDI BIDI","BEASTS",R.drawable.abaya)
        val the_wraith_from_paintings=ContentDetail("THE WRAITH FROM  PAINTINGS","BIDI BIDI","BEASTS",R.drawable.abaya)
        val therazane=ContentDetail("THERAZANE","BIDI BIDI","BEASTS",R.drawable.abaya)
        val three_little_pigs=ContentDetail("THREE LITTLE PIGS","BIDI BIDI","BEASTS",R.drawable.abaya)
        val ulfhedinn=ContentDetail("ULFHEDINN","BIDI BIDI","BEASTS",R.drawable.abaya)
        val umbra=ContentDetail("UMBRA","BIDI BIDI","BEASTS",R.drawable.abaya)
        val venomus_arachasae=ContentDetail("VENOMUS ARACHASAE","BIDI BIDI","BEASTS",R.drawable.abaya)
        val warg=ContentDetail("WARG","BIDI BIDI","BEASTS",R.drawable.abaya)
        val water_hag=ContentDetail("WATER HAG","BIDI BIDI","BEASTS",R.drawable.abaya)
        val werewolf=ContentDetail("WEREWOLF","BIDI BIDI","BEASTS",R.drawable.abaya)
        val wham_a_wham=ContentDetail("WHAM A WHAM","BIDI BIDI","BEASTS",R.drawable.abaya)
        val wicked_witch=ContentDetail("WICKED WITCH","BIDI BIDI","BEASTS",R.drawable.abaya)
        val wights=ContentDetail("WIGHTS","BIDI BIDI","BEASTS",R.drawable.abaya)
        val wild_boars=ContentDetail("WILD BOARS","BIDI BIDI","BEASTS",R.drawable.abaya)
        val wolves=ContentDetail("WOLVES","BIDI BIDI","BEASTS",R.drawable.abaya)
        val woodland_spirit=ContentDetail("WOODLAN SPIRIT","BIDI BIDI","BEASTS",R.drawable.abaya)
        val wraith=ContentDetail("WRAITH","BIDI BIDI","BEASTS",R.drawable.abaya)
        val wyvern=ContentDetail("WYVERN","BIDI BIDI","BEASTS",R.drawable.abaya)





        contentList.add(abaya)
        contentList.add(alghoul)
        contentList.add(alp)
        contentList.add(alpha_garkain)
        contentList.add(arachasae)
        contentList.add(armored_arachasae)
        contentList.add(barghest)
        contentList.add(basilisk)
        contentList.add(beannshie)
        contentList.add(bear)
        contentList.add(beast_of_beaculair)
        contentList.add(berserker)
        contentList.add(big_bad_wolf)
        contentList.add(botchlling)
        contentList.add(bruxae)
        contentList.add(chort)
        contentList.add(cloud_giant)
        contentList.add(cocktraice)
        contentList.add(crones)
        contentList.add(cyclopse)
        contentList.add(daphne_s_wraith)
        contentList.add(detlaff_van_der_eretein)
        contentList.add(devil_by_the_well)
        contentList.add(devour)
        contentList.add(djinn)
        contentList.add(dog)
        contentList.add(dopplers)
        contentList.add(drowned_dead)
        contentList.add(drowner)
        contentList.add(earth_elemental)
        contentList.add(ekhidnae)
        contentList.add(ekimmara)
        contentList.add(emiel_regis)
        contentList.add(endrega_drone)
        contentList.add(endrega_warrior)
        contentList.add(endrega_workers)
        contentList.add(erynias)
        contentList.add(ethereal)
        contentList.add(fiend)
        contentList.add(fire_elemental)
        contentList.add(fleder)
        contentList.add(foglet)
        contentList.add(forktail)
        contentList.add(fugas)
        contentList.add(gael)
        contentList.add(gargoyle)
        contentList.add(garkain)
        contentList.add(ghoul)
        contentList.add(giant_centipede)
        contentList.add(godling)
        contentList.add(golem)
        contentList.add(golyat)
        contentList.add(grave_hag)
        contentList.add(griffin)
        contentList.add(grottore)
        contentList.add(hagubman)
        contentList.add(harpy)
        contentList.add(harrisi)
        contentList.add(hound_of_the_wild_hunt)
        contentList.add(howler)
        contentList.add(hym)
        contentList.add(ice_elemental)
        contentList.add(ice_troll)
        contentList.add(ice_giant)
        contentList.add(ignis_fatuus)
        contentList.add(imp)
        contentList.add(jenny_o_the_woods)
        contentList.add(katakan)
        contentList.add(kernun)
        contentList.add(kikimore)
        contentList.add(kikimore_worker)
        contentList.add(leshen)
        contentList.add(longlocks)
        contentList.add(lubberkin)
        contentList.add(melusine)
        contentList.add(moreau_s_golem)
        contentList.add(morvudd)
        contentList.add(mourntart)
        contentList.add(mucknixer)
        contentList.add(nekker)
        contentList.add(nightwraith)
        contentList.add(noonwraith)
        contentList.add(opinicus)
        contentList.add(pale_widow)
        contentList.add(palgue_maiden)
        contentList.add(panther)
        contentList.add(penitent)
        contentList.add(pixie)
        contentList.add(protofleder)
        contentList.add(red_miasmal)
        contentList.add(rock_troll)
        contentList.add(rotfiend)
        contentList.add(royal_wyvern)
        contentList.add(salma)
        contentList.add(sandcrap)
        contentList.add(sarasti)
        contentList.add(scurvers)
        contentList.add(shaelmaar)
        contentList.add(shaelmaar_from_the_emperor_of_nilfgaard)
        contentList.add(shrieker)
        contentList.add(silver_basilisk)
        contentList.add(siren)
        contentList.add(slyzard)
        contentList.add(slyzard_matriarch)
        contentList.add(spotted_wight)
        contentList.add(spriggans)
        contentList.add(succubi)
        contentList.add(sylvan)
        contentList.add(the_apiarian_phantom)
        contentList.add(the_bruxa_of_corva_bianco)
        contentList.add(the_caretaker)
        contentList.add(the_dragon_pf_fyresdal)
        contentList.add(the_monster_of_tufo)
        contentList.add(the_toad_prince)
        contentList.add(the_unseen_elder)
        contentList.add(the_white_lady)
        contentList.add(the_wraith_from_paintings)
        contentList.add(therazane)
        contentList.add(three_little_pigs)
        contentList.add(ulfhedinn)
        contentList.add(umbra)
        contentList.add(venomus_arachasae)
        contentList.add(warg)
        contentList.add(water_hag)
        contentList.add(werewolf)
        contentList.add(wham_a_wham)
        contentList.add(wicked_witch)
        contentList.add(wights)
        contentList.add(wild_boars)
        contentList.add(wolves)
        contentList.add(woodland_spirit)
        contentList.add(wraith)
        contentList.add(wyvern)



        binding.recyclerView.layoutManager=LinearLayoutManager(this)
        val contentAdapter=ContentAdapter(contentList)
        binding.recyclerView.adapter=contentAdapter



    }
}